version: "3.4"

networks:
  cas-network:
    driver: bridge

services:
  mysql-db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_HOST: '172.18.0.1'
      MYSQL_ROOT_PASSWORD: mysql_db
      MYSQL_DATABASE: nam_0508
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql_db
    volumes:
      - ~/volumes/mysql_db:/var/lib/mysql_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5
