// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Purchase struct {
	ID          int32        `json:"id"`
	WagerID     int32        `json:"wager_id"`
	BuyingPrice float64      `json:"buying_price"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Wager struct {
	ID                  int32         `json:"id"`
	TotalWagerValue     int32         `json:"total_wager_value"`
	Odds                int32         `json:"odds"`
	SellingPercentage   int32         `json:"selling_percentage"`
	SellingPrice        float64       `json:"selling_price"`
	CurrentSellingPrice float64       `json:"current_selling_price"`
	PercentageSold      sql.NullInt32 `json:"percentage_sold"`
	AmountSold          sql.NullInt32 `json:"amount_sold"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	UpdatedAt           sql.NullTime  `json:"updated_at"`
}
