// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Image struct {
	ID       int32           `json:"id"`
	UserID   sql.NullInt32   `json:"user_id"`
	Path     sql.NullString  `json:"path"`
	Metadata json.RawMessage `json:"metadata"`
}

type User struct {
	ID       int32          `json:"id"`
	UserName sql.NullString `json:"user_name"`
	Password sql.NullString `json:"password"`
}
